
experiment:
  name: engrf_abs
  out_dir: outputs/engrf_abs
  seed: 42

data:
  kind: fastmri_mask
  # lfhf_pair
  train_lf_root: /home/omertaub/data/ULF_EnC_slices/training/LF
  train_hf_root: /home/omertaub/data/ULF_EnC_slices/training/HF
  val_lf_root: /home/omertaub/data/ULF_EnC_slices/val/LF
  val_hf_root: /home/omertaub/data/ULF_EnC_slices/val/HF

  # fastmri_mask
  train_root:   /home/omertaub/data/fastMRI_brain_DICOM_slices/train/HF
  val_root:     /home/omertaub/data/fastMRI_brain_DICOM_slices/val/HF


  img_size: [256, 256]
  
  # Alternative resize configuration (more explicit)
  # resize_to: [256, 256]  # [height, width] or null to disable
  # resize_mode: "bilinear"  # interpolation mode: "bilinear", "nearest", "bicubic"

model:
  pmrf_only: True        # <- remove trailing comma; lower-case booleans are fine
  posterior_mean: swinir # Options: unet, swinir
  # pmrf_sigma_s: 0.0
  
  # Posterior Mean: SwinIR configuration
  pm_swinir:
    in_chans: 1
    img_size: 256        # sets input_resolution internally
    window_size: 8      
    embed_dim: 60        # a light SwinIR-S variant (tweak as you wish)
    depths: [3, 3, 3, 3, 3]
    num_heads: [3, 3, 3, 3, 3]
    mlp_ratio: 2
    upsampler: ""        # empty string for denoising/restoration (no upscaling)
    resi_connection: "1conv"    # keep defaults if you prefer
    
  # Posterior Mean: UNet configuration (alternative)
  pm_unet:
    in_ch: 1
    out_ch: 1
    base_ch: 64
    depth: 4

  # Rectified Flow: Options - "unet", "hdit", "hourglass" (image_transformer_v2)
  rf_unet:
    arch: hourglass  # Options: unet, hdit, hourglass (or image_transformer_v2)
    in_channels: 1
    out_channels: 1
    
    # For legacy UNet (arch: unet)
    base_channels: 64
    depth: 4
    
    # For HDiT (arch: hdit) - default
    patch_size: 4
    local_widths: [384]
    local_depths: [2]
    global_width: 768
    global_depth: 11
    head_dim: 64
    natten_kernel: 7
    time_dim: 256
    time_mlp_hidden: 1024
    mlp_ratio: 4
    
    # For Hourglass / ImageTransformerV2 (arch: hourglass)
    # patch_size: [2, 2]  # Can be int or tuple
    mapping:
      depth: 2
      width: 256
      d_ff: 512
      dropout: 0.0
    levels:
      - depth: 4
        width: 256
        d_ff: 1024
        self_attn_type: neighborhood  # Options: global, neighborhood, shifted_window
        d_head: 64
        kernel_size: 7
        dropout: 0.0
      - depth: 4
        width: 512
        d_ff: 2048
        self_attn_type: global
        d_head: 64
        dropout: 0.0
  gauge_field:
    in_ch_img: 1
    in_ch_meas: 1
    hidden: 64
    depth: 4
  gauge_flow:
    steps: 4
    alpha_peak: 1.0

train:
  batch_size: 1
  num_workers: 1
  amp: true
  out_dir: outputs/engrf_abs
  lr_pm: 1.0e-4
  lr_stage1: 1.0e-4
  lr_stage2: 1.0e-4
  weight_decay: 1.0e-4
  grad_clip: 1.0
  epochs_stage0: 100
  epochs_stage1: 100
  epochs_stage2: 100
  log_interval: 500000
  val_every: 1
  vis_every: 1
  vis_n: 5
  lr_gamma: 0.9
  lr_step_every: 0
  lambda_conjugacy: 1.0
  ft_rf_in_stage2: false

