# Configuration for SwinIR Posterior Mean + Hourglass Rectified Flow
# This is a high-performance configuration using transformer-based architectures

experiment:
  name: engrf_swinir_hourglass
  out_dir: outputs/engrf_swinir_hourglass
  seed: 42

data:
  kind: fastmri_mask
  train_root: /home/omertaub/data/fastMRI_brain_DICOM_slices/train/HF
  val_root: /home/omertaub/data/fastMRI_brain_DICOM_slices/val/HF
  img_size: [128, 128]

model:
  pmrf_only: True
  posterior_mean: swinir
  
  # SwinIR Posterior Mean Configuration
  pm_swinir:
    in_chans: 1
    img_size: [128, 128]
    window_size: 4
    embed_dim: 60
    depths: [6, 6, 6, 6, 6, 6]
    num_heads: [6, 6, 6, 6, 6, 6]
    mlp_ratio: 2
    upsampler: ""
    resi_connection: "1conv"
  
  # Hourglass Rectified Flow Configuration
  rf_unet:
    arch: hourglass
    in_channels: 1
    out_channels: 1
    patch_size: 4          # fewer tokens than 2 → big win

    mapping:
      depth: 1
      width: 128
      d_ff: 256
      dropout: 0.0

    levels:
      # Level 0 (high-res): local attention, smaller & shallower
      - depth: 2
        width: 128         # was 160 → now divisible by 64
        d_ff: 512
        self_attn_type: neighborhood
        d_head: 64
        kernel_size: 5     # was 7
        dropout: 0.0

      # Level 1 (bottleneck): global attention, still slim
      - depth: 2
        width: 320         # 320 = 5 * 64 (OK)
        d_ff: 1280
        self_attn_type: global
        d_head: 64
        dropout: 0.0
  
  gauge_field:
    in_ch_img: 1
    in_ch_meas: 1
    hidden: 64
    depth: 4
  
  gauge_flow:
    steps: 4
    alpha_peak: 1.0

train:
  batch_size: 2
  num_workers: 1
  amp: true
  out_dir: outputs/engrf_swinir_hourglass
  lr_pm: 1.0e-4
  lr_stage1: 1.0e-4
  lr_stage2: 1.0e-4
  weight_decay: 1.0e-4
  grad_clip: 1.0
  epochs_stage0: 1000
  epochs_stage1: 100
  epochs_stage2: 100
  log_interval: 500000
  val_every: 1
  vis_every: 1
  vis_n: 5
  lr_gamma: 0.9
  lr_step_every: 0
  lambda_conjugacy: 1.0
  ft_rf_in_stage2: false

